# Generated by Django 4.2.18 on 2025-04-03 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_productimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimage",
            name="name",
        ),
    ]
